### ISSUE TITLE
Resizing column on nested table

### ISSUE THREAD

**Issue by bubach** [chanzuckerberg/czi-prosemirror#73]
When inserting a second table inside another one, column resizing on the parent table is acting real weird - I think the child table is pushing for 100% width or something. Also sometimes a new column will be inserted at the end of the parent table. Usually the resize handle gets stuck at that point, breaking the editor for any further adjustments.

**Comment by fabianx-ai** [comment]
So this is fixed now?

**Comment by hedgerwang** [comment]
@LionsAd : yes. It's fixed now.
